# Postgres
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14.2-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: "kl@p@uc1u5"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_DB
          value: "kubenews"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: rodrigoclemente/kube-news:2.0.0
        env:
        - name: "DB_DATABASE"
          value: "kubenews"
        - name: "DB_USERNAME"
          value: "postgres"
        - name: "DB_PASSWORD"
          value: "kl@p@uc1u5"
        - name: "DB_HOST"
          value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: NodePort

